### ISSUE TITLE
Update syntax for image alignment

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/keel#18]
``` scss
/**
 * Image alignment
 */

.aligncenter {
    display: block;
    text-align: center;
    margin-left: auto;
    margin-right: auto;
}

.alignleft {
    @extend .aligncenter;

    @media (min-width: $bp-small) {
        float: left;
        margin-right: calc-em(8px);
    }
}

.alignright {
    @extend .aligncenter;

    @media (min-width: $bp-small) {
        float: right;
        margin-left: calc-em(8px);
    }
}

.alignnone {
    @extend .aligncenter;

    @media (min-width: $bp-small) {
        margin-left: 0;
        margin-right: 0;
    }
}
```
